#spring:
#  rabbitmq:
#    host: 172.16.116.100
#    port: 5672
#    virtual-host: /fengge
#    username: fengge
#    password: fengge
#item:
#  rabbitmq:
#    exchange: GMALL-PMS-EXCHANGE


spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual